name: learn-github-actions
on: [push,workflow_dispatch]
jobs: 
    greet:
        runs-on: ubuntu-latest
        steps: 
            - name: Greet the world
              run: echo "Hello world!"

            - name: Getting Code
              # run: |
              #   git clone https://github.com/${{ github.repository }}.git
              uses: actions/checkout@v4

            - name: Installing NodeJS
              uses: actions/setup-node@v6
              with:
                  node-version: '20'


            - name: Print node version
              run: node -v

            - name: Install Dependencies
              run: npm ci