name: learn-github-actions
on: push
jobs: 
    greet:
        runs-on: ubuntu-latest
        steps: 
            - run: echo "Hello world!"
              name: Greet the world
            - name: Getting Code
              run: |
                https://github.com/${{ github.repository }}.git